### ISSUE TITLE
Port to Angelo

### ISSUE THREAD

**Issue by ungoldman** [ngoldman/martin#1]
Despite working almost exclusively with front-end mapping tools and node.js over the last two years my most popular contribution is still a Sinatra app boilerplate I made three years ago, so I might as well update it to use something decent like [Angelo](https://github.com/kenichi/angelo) (h/t @kenichi).

It should probably be versioned in some way too. Here we go!

![](http://media.giphy.com/media/oVvhEYvWDvE1G/giphy.gif)

**Comment by kenichi** [comment]
:+1: but sinatra definitely counts as "decent" :smiley_cat:

**Comment by ungoldman** [comment]
@kenichi true true

This repo is very dated though and updating it to use Angelo will give me a chance to (a) refamiliarize myself with Ruby, (b) get to know Angelo better, (c) make sure this thing with my name on it actually works, and (d) banish rack

**Comment by ungoldman** [comment]
nah
